### PR TITLE
manifestDest

### PR DESCRIPTION
**Pull request by johnpapa**
cc @jeffposnick

### CODE REVIEW

**Comment by jeffposnick** [comment]
Just want to loop in @gauntface on this to see if it makes sense to commit this PR. The changes were made in the upstream JSDocs at https://github.com/GoogleChrome/workbox/pull/602

It might be that we should wait for a new Workbox release, and then this updated text will be picked up in the new versioned docs for that release. Going back and updating previous versioned releases isn't the most scalable model. The flipside is that this was a typo and the fix applies equally to the older releases.

**Comment by gauntface** [comment]
@johnpapa Sorry, but I'm going to close this. The way our reference docs are built is directly from the github tags and these changes are likely to get overwritten :(

I have seen this get fixed in the source comments so next release should have this all fixed up.

**Comment by johnpapa** [comment]
k. for future reference, where should community contributions go?

**Comment by gauntface** [comment]
Reference-doc content is auto-generated from source code which is here: https://github.com/GoogleChrome/workbox/

Styling of reference docs or other pages is in this repo

**Pull request closed without merging**
